// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

export const buildVersion = async () => {
	const {build_version} = await getSatelliteExtendedActor({
		idlFactory
	});

	return await build_version();
}